layout: page
title: "Gramática Xavante"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jemoji
relative_links:
  enabled: true
  collections: true
