layout: page
title: "Gramática Xavante"
description: "Um estudo sobre o idioma xavante"
remote_theme: pages-themes/leap-day@v0.2.0
show_downloads: false
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
